### ISSUE TITLE
Create a launcher

### ISSUE THREAD

**Issue by eldon922** [SimonMarquis/Android-SoundQuickSettings#2]
Sometimes i need to access it from home screen or add it to shortcut like Quick Ball in Xiaomi devices. But it need the launcher to do that

**Comment by SimonMarquis** [comment]
Unfortunately this will go against the purpose of this project which aims to be minimalistic and to not provide any piece of user interface. Everything is controled by Android's System UI.
But you are welcome to fork this project if you want to.
