### ISSUE TITLE
Icon dimmed

### ISSUE THREAD

**Issue by argh0815** [SimonMarquis/Android-SoundQuickSettings#3]
Love the app, there is just one minor cosmetic issue on my setup (Lenovo Yoga Tab 13, Android 12):

When I pull down the status bar, the icon is dimmed.
![Screenshot_2022-11-19-22-44-24-605](https://user-images.githubusercontent.com/34507470/202872820-06d5c5d9-5eea-4f74-bc7e-9f2e3b849c0a.png)

But when I fully extend the bar, the icon is displayed properly. Not sure whether this is a bug in my Android version or whether something could be done on the app side.
![Screenshot_2022-11-19-22-44-46-393](https://user-images.githubusercontent.com/34507470/202872877-c148e9df-2a27-4985-b571-8665707e3349.png)

**Comment by SimonMarquis** [comment]
Hi @argh0815, not sure why this happens on your device.
I've force the "Active mode" in the new [1.0.4](https://github.com/SimonMarquis/Android-SoundQuickSettings/releases/tag/1.0.4) version.
Can you reproduce the issue on this version?

**Comment by argh0815** [comment]
This seems to have done the trick, thanks a ton! Your super quick response and fix are very much appreciated.
