### ISSUE TITLE
Long-tap triggers PIP

### ISSUE THREAD

**Issue by argh0815** [SimonMarquis/Android-SoundQuickSettings#5]
Similar to issue #1, picture-in-picture mode is triggered when I long-tap the tile to open the sound panel. Not sure whether something can be done about this.

**Comment by SimonMarquis** [comment]
Hi @argh0815, what Android version are you running?
I'm not able to reproduce this behavior on Android 13.

**Comment by argh0815** [comment]
It happens on 2 devices, one with 12, the other one with 13. Sorry, when I wrote long-tap I meant long-press which opens the panel at the bottom with volume for ringer, notifications, etc. The PIP gets triggered when watching a YouTube video while long-pressing the tile. When the video is paused, PIP doesn't get triggered.
