### ISSUE TITLE
Release at F-Droid

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimonMarquis/Android-SoundQuickSettings#6]
It would be awesome to have a release at [F-Droid](https://f-droid.org/).

**Comment by SimonMarquis** [comment]
:construction: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14587

**Comment by SimonMarquis** [comment]
@KrasnayaPloshchad the latest version is now available on F-Droid: https://f-droid.org/packages/fr.smarquis.soundquicksettings/
